# Example configuration

# If your database library is thread safe you can enable
# parallel execution of SQLs per database connections
multithread: no
# Poll interall in seconds
poll_interval: 10

# token can be specified by SLACK_TOKEN environment variable
slack:
  # slack web api token, you can get one from here: https://api.slack.com/web
  token: <foo>
  # bot's name. Can be anything
  username: csicska

databases:
  - name: First DB Connection
    connection-uri: jdbc:h2:mem:test_mem
    user: sa
    password: ""
    statements:
    - name: no output
      channel: "#test"
      type: simple
      query: SELECT 1 WHERE 1 = 0
    - name: bad query
      type: simple
      channel: "#test"
      query: SELECT 1 WHERE 1 = # bad query
    - name: two lines, two columns
      type: simple
      channel: "#test"
      query: SELECT 1 col1, 2 col2 union all select 3 col1, 4 col2
  - name: Second DB Connection
    connection-uri: jdbc:h2:mem:test_mem2
    user: sa
    password: ""
    statements:
    - name: using
      channel: "#test"
      type: simple
      # multi line queries can be added with > or | signs
      query: |
        SELECT '%WINDOW_START_DATETIME%' as "Cycle Started at"
             , '%WINDOW_END_DATETIME%' as "Cycle Ended at"

