# Example configuration

# If your database library is thread safe you can enable
# parallel execution of SQLs per database connections
multithread: no
# Poll interall in seconds
poll_interval: 10

# token can be specified by SLACK_TOKEN environment variable
slack:
  # slack web api token, you can get one from here: https://api.slack.com/web
  token: <foo>
  # bot's name. Can be anything
  username: csicska

databases:
  - name: db1_example
    connection-uri: jdbc:h2:mem:test_mem
    user: sa
    password: ""
    statements:
    - name: example1
      channel: "#test"
      type: simple
      query: SELECT 1
    - name: example2
      type: simple
      channel: "#test"
      query: SELECT 1 WHERE 1 = # bad query
    - name: example4
      type: simple
      channel: "#test"
      query: SELECT 1 col union all select 2 col
  - name: db2_example
    connection-uri: jdbc:h2:mem:test_mem2
    user: sa
    password: ""
    statements:
    - name: example3
      channel: "#test"
      type: simple
      query: SELECT '%WINDOW_START_DATETIME%' as start, '%WINDOW_END_DATETIME%' as end

