# Example configuration for monitoring failed talend jobs

# If your database library is thread safe you can enable
# parallel execution of SQLs per database connections
multithread: yes
# Poll interall in seconds
poll_interval: 300

# token can be specified by SLACK_TOKEN environment variable
slack:
  # slack web api token, you can get one from here: https://api.slack.com/web
  token: ADDME
  # bot's name. Can be anything
  username: talend_bot

databases:
  - name: Talend Prod
    connection-uri: "jdbc:oracle:thin:@//talend_server:1521/tac"
    user: tac
    password: "secret12"
    statements:
    - name: Failed jobs
      channel: "#talend_monitoring"
      type: simple
      query: |
        SELECT tasklabel FROM taskexecutionhistory WHERE detailedstatus IN ('KILLED', 'ALREADY_PROCESSING_ERROR',
        'UNEXPECTED_ERROR', 'RUNNING_ERROR' , 'ENDED_WITH_UNKNOWN_STATE' ,'JOB_ERROR', 'GENERATING_ERROR' )
        and taskenddate >= to_timestamp_tz( '%WINDOW_START_DATETIME%', 'YYYY-MM-DD"T"HH24:MI:SSTZH:TZM')
        and taskenddate < to_timestamp_tz( '%WINDOW_END_DATETIME%', 'YYYY-MM-DD"T"HH24:MI:SSTZH:TZM')
